### ISSUE TITLE
Smart contract / wallet set up

### ISSUE THREAD

**Issue by Buky33** [razvanstatescu/elrond-sft#1]
Hello,
Thanks for this project, very interesting to deal with SFT for once.
I have a question before investigating further on the possibilities of your project, concerning the smart contract, have you published the source code of the SC somewhere so that I can make it evolve as well?
Can I configure somewhere my own wallet to receive royalties from SFT sales?
++ Good job anyway, it's a really interesting project

**Comment by razvanstatescu** [comment]
> Hello, Thanks for this project, very interesting to deal with SFT for once. I have a question before investigating further on the possibilities of your project, concerning the smart contract, have you published the source code of the SC somewhere so that I can make it evolve as well? Can I configure somewhere my own wallet to receive royalties from SFT sales? ++ Good job anyway, it's a really interesting project

Hi, it's not using a SC. It's just using a normal wallet. And yes, because that wallet will be the creator of the SFT it will receive all the royalties.

**Comment by Buky33** [comment]
Hey, thanks for your reply, sorry for the delay, I didn't take the time to. Moreover it's really cool of you :)

Do you think it is also possible to burn an sft directly from a wallet, in that case how to secure the fact that we don't burn any SFT from any collection (except the one we would have issued ourselves)?

**Comment by Buky33** [comment]
Of course, I mean, is it possible to burn an SFT that you have already dropped to a wallet, and still of course that this wallet owner would have to make an action / authorize the action in some way ^^

**Comment by Buky33** [comment]
Let me explain what I'm trying to do:
I would drop some SFTs to specific wallets (challenge winner, giveaways, ...) -> this part seems easy, thanks to your project 👍
then I would open an action (from a website or any other tool) where they could convert it to something else, like an NFT, or whatever -> this action would burn the SFT and create an NFT that I could send back directly -> I am already OK on this last part

But I am still looking for the SFT burn part :)

**Comment by Buky33** [comment]
Or maybe I am trying to do a totally stupid thing, do not hesitate to tell me if you think I do ^^
